/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_Type.h
 * Generated on: Wed May 1 6:2:58 EET
 ********************************************************************/

#ifndef RTE_TYPE_H
#define RTE_TYPE_H


#include "Rte.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */
/**************************** datatypes ******************************/



/********************* mode declaration groups ***********************/


/********************** per instance memories ************************/


/******************* implicit buffer declaration *********************/

typedef struct {
	uint8 value;
} Rte_DE_uint8;


/******************** component data structures **********************/

/*********************************************************************
 * component data structure for SWC: Algo_App_SWC 
 *********************************************************************/
typedef struct Rte_CDS_Algo_App_SWC
{
	/* Data Handles section*/
	Rte_DE_uint8 *GetDoorStatusRunnable_RP_APP_SWC_DoorStatus;
	Rte_DE_uint8 *GetDoorStatusRunnable_PP_APP_SWC_LedStatus;
	/* Per-Instance Memory Handles section*/
	/* Inter-runnable Variable Handles section*/
	/* Calibration Parameter Handles section*/
	/* Exclusive-area Handles section*/
	/* Port API Handles section*/
	/* Inter Runnable Variable API Handles section*/
} Rte_CDS_Algo_App_SWC;

/*********************************************************************
 * component data structure for SWC: SA1_SWC 
 *********************************************************************/
typedef struct Rte_CDS_SA1_SWC
{
	/* Data Handles section*/
	Rte_DE_uint8 *GetDoorStatus_IO_SA1_RP_SA1_SWC_DoorStatus;
	Rte_DE_uint8 *GetDoorStatus_IO_SA1_PP_SA1_SWC_DoorStatus;
	/* Per-Instance Memory Handles section*/
	/* Inter-runnable Variable Handles section*/
	/* Calibration Parameter Handles section*/
	/* Exclusive-area Handles section*/
	/* Port API Handles section*/
	/* Inter Runnable Variable API Handles section*/
} Rte_CDS_SA1_SWC;

/*********************************************************************
 * component data structure for SWC: SA2_SWC 
 *********************************************************************/
typedef struct Rte_CDS_SA2_SWC
{
	/* Data Handles section*/
	Rte_DE_uint8 *GetDoorStatus_RP1_SA2_SWC_LedStatus;
	/* Per-Instance Memory Handles section*/
	/* Inter-runnable Variable Handles section*/
	/* Calibration Parameter Handles section*/
	/* Exclusive-area Handles section*/
	/* Port API Handles section*/
	/* Inter Runnable Variable API Handles section*/
} Rte_CDS_SA2_SWC;

/*********************************************************************
 * component data structure for SWC: IO_SWC 
 *********************************************************************/
typedef struct Rte_CDS_IO_SWC
{
	/* Data Handles section*/
	Rte_DE_uint8 *ReadDoorStatus_PP_IO_SWC_DoorStatus;
	/* Per-Instance Memory Handles section*/
	/* Inter-runnable Variable Handles section*/
	/* Calibration Parameter Handles section*/
	/* Exclusive-area Handles section*/
	/* Port API Handles section*/
	/* Inter Runnable Variable API Handles section*/
} Rte_CDS_IO_SWC;

/*********************************************************************
 * component data structure for SWC: RootCompisite 
 *********************************************************************/
typedef struct Rte_CDS_RootCompisite
{
	/* Data Handles section*/
	/* Per-Instance Memory Handles section*/
	/* Inter-runnable Variable Handles section*/
	/* Calibration Parameter Handles section*/
	/* Exclusive-area Handles section*/
	/* Port API Handles section*/
	/* Inter Runnable Variable API Handles section*/
	uint8 _dummy;
} Rte_CDS_RootCompisite;


#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* RTE_TYPE_H */
