/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_IO_SWC.h
 * Generated on: Wed May 1 6:2:58 EET
 ********************************************************************/

#ifndef RTE_IO_SWC_H
#define RTE_IO_SWC_H

#include "Rte_IO_SWC_Type.h"

#ifdef __cplusplus
	extern "C" {
#endif /* __cplusplus */

/**************** component data structure definition ****************/

#ifndef IN_RTE_C
typedef const Rte_CDS_IO_SWC * const Rte_Instance;
#endif

/************************* instance handle ***************************/

extern const Rte_CDS_IO_SWC * const Rte_Inst_IO_SWC;

/************************ application errors *************************/

#define RTE_E_IO_SA2_Led_Switch_E_OK ((Std_ReturnType)0)
#define RTE_E_IO_SA2_Led_Switch_E_Not_Ok ((Std_ReturnType)1)

/*************************** init values *****************************/


/****************** per instance memory definition *******************/


/************************* exclusive areas ***************************/


/************************* RTE API mapping ***************************/

/*****************************************************
 * Port: 		PPS_IO_SWC
 * Interface:	IO_SA2_Led_Switch
 * Operation:	Led_Switch
 *****************************************************/
extern Std_ReturnType LedSwitch(uint8 LedStatus) ;

/*****************************************************
 * Port: 		PP_IO_SWC
 * Interface:	IO_SA1_SRI
 * DataElement:	DoorStatus
 * Runnable:	ReadDoorStatus
 *****************************************************/
extern void Rte_IWrite_IO_SWC_ReadDoorStatus_PP_IO_SWC_DoorStatus (uint8 DoorStatus);
#ifndef IN_RTE_C
#define Rte_IWrite_ReadDoorStatus_PP_IO_SWC_DoorStatus(RTEData) \
	Rte_IWrite_IO_SWC_ReadDoorStatus_PP_IO_SWC_DoorStatus(RTEData)
#endif
extern uint8* Rte_IWriteRef_IO_SWC_ReadDoorStatus_PP_IO_SWC_DoorStatus(void);
#ifndef IN_RTE_C
#define Rte_IWriteRef_ReadDoorStatus_PP_IO_SWC_DoorStatus() \
	Rte_IWriteRef_IO_SWC_ReadDoorStatus_PP_IO_SWC_DoorStatus()
#endif


/**************** event triggered runnable entities *******************/

/*****************************************************
 * Runnable: 	ReadDoorStatus
 * Period:		0.01
 *****************************************************/
extern void SendDoorStatuToSA1(void);


/******** ARUnit-specific function pointers for server call delegates *********/


#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* RTE_IO_SWC_H */
