/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_SA2_SWC_.c
 * Generated on: Wed May 1 6:2:58 EET
 ********************************************************************/

#include "string.h"
#include "Rte_SA2_SWC.h"


Rte_DE_uint8 GetDoorStatus_RP1_SA2_SWC_LedStatus;


const Rte_CDS_SA2_SWC Rte_Instance_SA2_SWC = {
&GetDoorStatus_RP1_SA2_SWC_LedStatus
};

const Rte_CDS_SA2_SWC * const Rte_Inst_SA2_SWC = &Rte_Instance_SA2_SWC;


Std_ReturnType SA2_SWC_RP2_SA2_SWC_Led_Switch_Buffer_retcode = RTE_E_OK;

FunctionPtr_SA2_SWC_RP2_SA2_SWC_Led_Switch Rte_Call_SA2_SWC_RP2_SA2_SWC_Led_Switch_Delegate = 0;

uint8 Rte_IRead_SA2_SWC_GetDoorStatus_RP1_SA2_SWC_LedStatus (void)
{
	return (Rte_Inst_SA2_SWC)->GetDoorStatus_RP1_SA2_SWC_LedStatus->value;
}
Std_ReturnType Rte_Call_SA2_SWC_RP2_SA2_SWC_Led_Switch (uint8 LedStatus)
{
	Std_ReturnType __result = SA2_SWC_RP2_SA2_SWC_Led_Switch_Buffer_retcode;
	if ( Rte_Call_SA2_SWC_RP2_SA2_SWC_Led_Switch_Delegate != 0 ) {
		__result = Rte_Call_SA2_SWC_RP2_SA2_SWC_Led_Switch_Delegate(LedStatus);
	}
	return __result;
}
