/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_SA1_SWC_Type.h
 * Generated on: Wed May 1 6:2:58 EET
 ********************************************************************/

#ifndef RTE_SA1_SWC_TYPE_H
#define RTE_SA1_SWC_TYPE_H


#include "Rte_Type.h"

#ifdef __cplusplus
	extern "C" {
#endif /* __cplusplus */

/*************************** range types *****************************/


/************************ enumeration types **************************/



#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* RTE_SA1_SWC_TYPE_H */
