/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_Algo_App_SWC.h
 * Generated on: Wed May 1 6:2:58 EET
 ********************************************************************/

#ifndef RTE_ALGO_APP_SWC_H
#define RTE_ALGO_APP_SWC_H

#include "Rte_Algo_App_SWC_Type.h"

#ifdef __cplusplus
	extern "C" {
#endif /* __cplusplus */

/**************** component data structure definition ****************/

#ifndef IN_RTE_C
typedef const Rte_CDS_Algo_App_SWC * const Rte_Instance;
#endif

/************************* instance handle ***************************/

extern const Rte_CDS_Algo_App_SWC * const Rte_Inst_Algo_App_SWC;

/************************ application errors *************************/


/*************************** init values *****************************/


/****************** per instance memory definition *******************/


/************************* exclusive areas ***************************/


/************************* RTE API mapping ***************************/

/*****************************************************
 * Port: 		RP_APP_SWC
 * Interface:	SA1_APP_SRI
 * DataElement:	DoorStatus
 * Runnable:	GetDoorStatusRunnable
 *****************************************************/
extern uint8 Rte_IRead_Algo_App_SWC_GetDoorStatusRunnable_RP_APP_SWC_DoorStatus (void);
#ifndef IN_RTE_C
#define Rte_IRead_GetDoorStatusRunnable_RP_APP_SWC_DoorStatus() \
	Rte_IRead_Algo_App_SWC_GetDoorStatusRunnable_RP_APP_SWC_DoorStatus()
#endif

/*****************************************************
 * Port: 		PP_APP_SWC
 * Interface:	APP_SA2_SRI
 * DataElement:	LedStatus
 * Runnable:	GetDoorStatusRunnable
 *****************************************************/
extern void Rte_IWrite_Algo_App_SWC_GetDoorStatusRunnable_PP_APP_SWC_LedStatus (uint8 LedStatus);
#ifndef IN_RTE_C
#define Rte_IWrite_GetDoorStatusRunnable_PP_APP_SWC_LedStatus(RTEData) \
	Rte_IWrite_Algo_App_SWC_GetDoorStatusRunnable_PP_APP_SWC_LedStatus(RTEData)
#endif
extern uint8* Rte_IWriteRef_Algo_App_SWC_GetDoorStatusRunnable_PP_APP_SWC_LedStatus(void);
#ifndef IN_RTE_C
#define Rte_IWriteRef_GetDoorStatusRunnable_PP_APP_SWC_LedStatus() \
	Rte_IWriteRef_Algo_App_SWC_GetDoorStatusRunnable_PP_APP_SWC_LedStatus()
#endif


/**************** event triggered runnable entities *******************/

/*****************************************************
 * Runnable: 	GetDoorStatusRunnable
 * Period:		0.015
 *****************************************************/
extern void GetDoorStatusFromSA1(void);


/******** ARUnit-specific function pointers for server call delegates *********/


#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* RTE_ALGO_APP_SWC_H */
