/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_SA1_SWC_.c
 * Generated on: Wed May 1 4:53:4 EET
 ********************************************************************/

#include "string.h"
#include "Rte_SA1_SWC.h"

extern Rte_DE_uint8 ReadDoorStatus_PP_IO_SWC_DoorStatus;

Rte_DE_uint8 GetDoorStatus_IO_SA1_PP_SA1_SWC_DoorStatus;


const Rte_CDS_SA1_SWC Rte_Instance_SA1_SWC = {
&ReadDoorStatus_PP_IO_SWC_DoorStatus,
&GetDoorStatus_IO_SA1_PP_SA1_SWC_DoorStatus
};

const Rte_CDS_SA1_SWC * const Rte_Inst_SA1_SWC = &Rte_Instance_SA1_SWC;




void Rte_IWrite_SA1_SWC_GetDoorStatus_IO_SA1_PP_SA1_SWC_DoorStatus (uint8 DoorStatus)
{
	(Rte_Inst_SA1_SWC)->GetDoorStatus_IO_SA1_PP_SA1_SWC_DoorStatus->value = DoorStatus;
}
uint8* Rte_IWriteRef_SA1_SWC_GetDoorStatus_IO_SA1_PP_SA1_SWC_DoorStatus(void)
{
	return &(Rte_Inst_SA1_SWC)->GetDoorStatus_IO_SA1_PP_SA1_SWC_DoorStatus->value;
}
uint8 Rte_IRead_SA1_SWC_GetDoorStatus_IO_SA1_RP_SA1_SWC_DoorStatus (void)
{
	return (Rte_Inst_SA1_SWC)->GetDoorStatus_IO_SA1_RP_SA1_SWC_DoorStatus->value;
}
