/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_SA2_SWC.h
 * Generated on: Wed May 1 6:2:58 EET
 ********************************************************************/

#ifndef RTE_SA2_SWC_H
#define RTE_SA2_SWC_H

#include "Rte_SA2_SWC_Type.h"

#ifdef __cplusplus
	extern "C" {
#endif /* __cplusplus */

/**************** component data structure definition ****************/

#ifndef IN_RTE_C
typedef const Rte_CDS_SA2_SWC * const Rte_Instance;
#endif

/************************* instance handle ***************************/

extern const Rte_CDS_SA2_SWC * const Rte_Inst_SA2_SWC;

/************************ application errors *************************/

#define RTE_E_IO_SA2_Led_Switch_E_OK ((Std_ReturnType)0)
#define RTE_E_IO_SA2_Led_Switch_E_Not_Ok ((Std_ReturnType)1)

/*************************** init values *****************************/


/****************** per instance memory definition *******************/


/************************* exclusive areas ***************************/


/************************* RTE API mapping ***************************/

/*****************************************************
 * Port: 		RP1_SA2_SWC
 * Interface:	APP_SA2_SRI
 * DataElement:	LedStatus
 * Runnable:	GetDoorStatus
 *****************************************************/
extern uint8 Rte_IRead_SA2_SWC_GetDoorStatus_RP1_SA2_SWC_LedStatus (void);
#ifndef IN_RTE_C
#define Rte_IRead_GetDoorStatus_RP1_SA2_SWC_LedStatus() \
	Rte_IRead_SA2_SWC_GetDoorStatus_RP1_SA2_SWC_LedStatus()
#endif

/*****************************************************
 * Port: 		RP2_SA2_SWC
 * Interface:	IO_SA2_Led_Switch
 * Operation:	Led_Switch
 * Sync/Async:	Synchronous
 *****************************************************/
extern Std_ReturnType Rte_Call_SA2_SWC_RP2_SA2_SWC_Led_Switch (uint8 LedStatus);
#ifndef IN_RTE_C
#define Rte_Call_RP2_SA2_SWC_Led_Switch(LedStatus) \
	Rte_Call_SA2_SWC_RP2_SA2_SWC_Led_Switch(LedStatus)
#endif


/**************** event triggered runnable entities *******************/

/*****************************************************
 * Runnable: 	GetDoorStatus
 * Period:		0.018
 *****************************************************/
extern void GetDoorStatusFromApp(void);


/******** ARUnit-specific function pointers for server call delegates *********/
typedef Std_ReturnType (*FunctionPtr_SA2_SWC_RP2_SA2_SWC_Led_Switch)(uint8 LedStatus);


#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* RTE_SA2_SWC_H */
