/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_SA1_SWC.h
 * Generated on: Wed May 1 4:53:4 EET
 ********************************************************************/

#ifndef RTE_SA1_SWC_H
#define RTE_SA1_SWC_H

#include "Rte_SA1_SWC_Type.h"

#ifdef __cplusplus
	extern "C" {
#endif /* __cplusplus */

/**************** component data structure definition ****************/

#ifndef IN_RTE_C
typedef const Rte_CDS_SA1_SWC * const Rte_Instance;
#endif

/************************* instance handle ***************************/

extern const Rte_CDS_SA1_SWC * const Rte_Inst_SA1_SWC;

/************************ application errors *************************/


/*************************** init values *****************************/


/****************** per instance memory definition *******************/


/************************* exclusive areas ***************************/


/************************* RTE API mapping ***************************/

/*****************************************************
 * Port: 		PP_SA1_SWC
 * Interface:	SA1_APP_SRI
 * DataElement:	DoorStatus
 * Runnable:	GetDoorStatus_IO_SA1
 *****************************************************/
extern void Rte_IWrite_SA1_SWC_GetDoorStatus_IO_SA1_PP_SA1_SWC_DoorStatus (uint8 DoorStatus);
#ifndef IN_RTE_C
#define Rte_IWrite_GetDoorStatus_IO_SA1_PP_SA1_SWC_DoorStatus(RTEData) \
	Rte_IWrite_SA1_SWC_GetDoorStatus_IO_SA1_PP_SA1_SWC_DoorStatus(RTEData)
#endif
extern uint8* Rte_IWriteRef_SA1_SWC_GetDoorStatus_IO_SA1_PP_SA1_SWC_DoorStatus(void);
#ifndef IN_RTE_C
#define Rte_IWriteRef_GetDoorStatus_IO_SA1_PP_SA1_SWC_DoorStatus() \
	Rte_IWriteRef_SA1_SWC_GetDoorStatus_IO_SA1_PP_SA1_SWC_DoorStatus()
#endif

/*****************************************************
 * Port: 		RP_SA1_SWC
 * Interface:	IO_SA1_SRI
 * DataElement:	DoorStatus
 * Runnable:	GetDoorStatus_IO_SA1
 *****************************************************/
extern uint8 Rte_IRead_SA1_SWC_GetDoorStatus_IO_SA1_RP_SA1_SWC_DoorStatus (void);
#ifndef IN_RTE_C
#define Rte_IRead_GetDoorStatus_IO_SA1_RP_SA1_SWC_DoorStatus() \
	Rte_IRead_SA1_SWC_GetDoorStatus_IO_SA1_RP_SA1_SWC_DoorStatus()
#endif


/**************** event triggered runnable entities *******************/

/*****************************************************
 * Runnable: 	GetDoorStatus_IO_SA1
 * Period:		0.012
 *****************************************************/
extern void GetDoorStatusFromIO(void);


/******** ARUnit-specific function pointers for server call delegates *********/


#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* RTE_SA1_SWC_H */
