/********************************************************************
 * Automatically generated by ARUnit
 * Filename: ARUnit_Algo_App_SWC_.c
 * Generated on: Wed May 1 6:2:58 EET
 ********************************************************************/

#include "string.h"
#include "ARUnit_Algo_App_SWC.h"


extern const Rte_CDS_Algo_App_SWC Rte_Instance_Algo_App_SWC;
extern const Rte_CDS_Algo_App_SWC * const Rte_Inst_Algo_App_SWC;




DECLSPEC_EXPORT void ARUnit_IWrite_Algo_App_SWC_GetDoorStatusRunnable_RP_APP_SWC_DoorStatus(uint8 DoorStatus)
{
	(Rte_Inst_Algo_App_SWC)->GetDoorStatusRunnable_RP_APP_SWC_DoorStatus->value = DoorStatus;
}
DECLSPEC_EXPORT uint8* ARUnit_IWriteRef_Algo_App_SWC_GetDoorStatusRunnable_RP_APP_SWC_DoorStatus(void)
{
	return &(Rte_Inst_Algo_App_SWC)->GetDoorStatusRunnable_RP_APP_SWC_DoorStatus->value;
}
DECLSPEC_EXPORT uint8 ARUnit_IRead_Algo_App_SWC_GetDoorStatusRunnable_RP_APP_SWC_DoorStatus(void)
{
	return (Rte_Inst_Algo_App_SWC)->GetDoorStatusRunnable_RP_APP_SWC_DoorStatus->value;
}
DECLSPEC_EXPORT void ARUnit_IWrite_Algo_App_SWC_GetDoorStatusRunnable_PP_APP_SWC_LedStatus(uint8 LedStatus)
{
		(Rte_Inst_Algo_App_SWC)->GetDoorStatusRunnable_PP_APP_SWC_LedStatus->value = LedStatus;
}
DECLSPEC_EXPORT uint8* ARUnit_IWriteRef_Algo_App_SWC_GetDoorStatusRunnable_PP_APP_SWC_LedStatus(void)
{
	return &(Rte_Inst_Algo_App_SWC)->GetDoorStatusRunnable_PP_APP_SWC_LedStatus->value;
}
DECLSPEC_EXPORT uint8 ARUnit_IRead_Algo_App_SWC_GetDoorStatusRunnable_PP_APP_SWC_LedStatus(void)
{
	return (Rte_Inst_Algo_App_SWC)->GetDoorStatusRunnable_PP_APP_SWC_LedStatus->value;
}


DECLSPEC_EXPORT void ARUnit_Trigger_Algo_App_SWC_GetDoorStatusFromSA1(void)
{
	GetDoorStatusFromSA1();
}
