/********************************************************************
 * Automatically generated by ARUnit
 * Filename: ARUnit_SA2_SWC.h
 * Generated on: Wed May 1 6:2:58 EET
 ********************************************************************/

#include "Rte_SA2_SWC.h"	

#ifndef ARUNIT_SA2_SWC_H
#define ARUNIT_SA2_SWC_H

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef false
    #define false (0)
#endif
#ifndef true
    #define true  (!false)
#endif


void ARUnit_Initialize ();

/***************************************/
/******** Delegates API  ***************/
/***************************************/
DECLSPEC_EXPORT void ARUnit_Set_SA2_SWC_RP2_SA2_SWC_Led_Switch_Delegate(FunctionPtr_SA2_SWC_RP2_SA2_SWC_Led_Switch );
DECLSPEC_EXPORT void ARUnit_Call_SA2_SWC_RP2_SA2_SWC_Led_Switch_ReturnCode(Std_ReturnType returnCode);

/***************************************/
/******** Flags API  *******************/
/***************************************/

/***************************************/
/******** Implicit API  ****************/
/***************************************/
DECLSPEC_EXPORT void ARUnit_IWrite_SA2_SWC_GetDoorStatus_RP1_SA2_SWC_LedStatus(uint8 LedStatus);
DECLSPEC_EXPORT uint8 ARUnit_IRead_SA2_SWC_GetDoorStatus_RP1_SA2_SWC_LedStatus(void);
DECLSPEC_EXPORT uint8* ARUnit_IWriteRef_SA2_SWC_GetDoorStatus_RP1_SA2_SWC_LedStatus(void);
/***************************************/
/******** Explicit API  ****************/
/***************************************/
/***************************************/
/******** Runnable Calls****************/
/***************************************/

DECLSPEC_EXPORT void ARUnit_Trigger_SA2_SWC_GetDoorStatusFromApp(void);

#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* ARUNIT_SA2_SWC_H */
