/********************************************************************
 * Automatically generated by ARUnit
 * Filename: ARUnit_IO_SWC_.c
 * Generated on: Wed May 1 6:2:58 EET
 ********************************************************************/

#include "string.h"
#include "ARUnit_IO_SWC.h"


extern const Rte_CDS_IO_SWC Rte_Instance_IO_SWC;
extern const Rte_CDS_IO_SWC * const Rte_Inst_IO_SWC;




DECLSPEC_EXPORT Std_ReturnType ARUnit_Trigger_IO_SWC_LedSwitch(uint8 LedStatus)
{
	return LedSwitch(LedStatus);
}
DECLSPEC_EXPORT void ARUnit_IWrite_IO_SWC_ReadDoorStatus_PP_IO_SWC_DoorStatus(uint8 DoorStatus)
{
		(Rte_Inst_IO_SWC)->ReadDoorStatus_PP_IO_SWC_DoorStatus->value = DoorStatus;
}
DECLSPEC_EXPORT uint8* ARUnit_IWriteRef_IO_SWC_ReadDoorStatus_PP_IO_SWC_DoorStatus(void)
{
	return &(Rte_Inst_IO_SWC)->ReadDoorStatus_PP_IO_SWC_DoorStatus->value;
}
DECLSPEC_EXPORT uint8 ARUnit_IRead_IO_SWC_ReadDoorStatus_PP_IO_SWC_DoorStatus(void)
{
	return (Rte_Inst_IO_SWC)->ReadDoorStatus_PP_IO_SWC_DoorStatus->value;
}


DECLSPEC_EXPORT void ARUnit_Trigger_IO_SWC_SendDoorStatuToSA1(void)
{
	SendDoorStatuToSA1();
}
