/********************************************************************
 * Automatically generated by ARUnit
 * Filename: ARUnit_SA1_SWC_.c
 * Generated on: Wed May 1 6:2:58 EET
 ********************************************************************/

#include "string.h"
#include "ARUnit_SA1_SWC.h"


extern const Rte_CDS_SA1_SWC Rte_Instance_SA1_SWC;
extern const Rte_CDS_SA1_SWC * const Rte_Inst_SA1_SWC;




DECLSPEC_EXPORT void ARUnit_IWrite_SA1_SWC_GetDoorStatus_IO_SA1_PP_SA1_SWC_DoorStatus(uint8 DoorStatus)
{
		(Rte_Inst_SA1_SWC)->GetDoorStatus_IO_SA1_PP_SA1_SWC_DoorStatus->value = DoorStatus;
}
DECLSPEC_EXPORT uint8* ARUnit_IWriteRef_SA1_SWC_GetDoorStatus_IO_SA1_PP_SA1_SWC_DoorStatus(void)
{
	return &(Rte_Inst_SA1_SWC)->GetDoorStatus_IO_SA1_PP_SA1_SWC_DoorStatus->value;
}
DECLSPEC_EXPORT uint8 ARUnit_IRead_SA1_SWC_GetDoorStatus_IO_SA1_PP_SA1_SWC_DoorStatus(void)
{
	return (Rte_Inst_SA1_SWC)->GetDoorStatus_IO_SA1_PP_SA1_SWC_DoorStatus->value;
}
DECLSPEC_EXPORT void ARUnit_IWrite_SA1_SWC_GetDoorStatus_IO_SA1_RP_SA1_SWC_DoorStatus(uint8 DoorStatus)
{
	(Rte_Inst_SA1_SWC)->GetDoorStatus_IO_SA1_RP_SA1_SWC_DoorStatus->value = DoorStatus;
}
DECLSPEC_EXPORT uint8* ARUnit_IWriteRef_SA1_SWC_GetDoorStatus_IO_SA1_RP_SA1_SWC_DoorStatus(void)
{
	return &(Rte_Inst_SA1_SWC)->GetDoorStatus_IO_SA1_RP_SA1_SWC_DoorStatus->value;
}
DECLSPEC_EXPORT uint8 ARUnit_IRead_SA1_SWC_GetDoorStatus_IO_SA1_RP_SA1_SWC_DoorStatus(void)
{
	return (Rte_Inst_SA1_SWC)->GetDoorStatus_IO_SA1_RP_SA1_SWC_DoorStatus->value;
}


DECLSPEC_EXPORT void ARUnit_Trigger_SA1_SWC_GetDoorStatusFromIO(void)
{
	GetDoorStatusFromIO();
}
