/********************************************************************
 * Automatically generated by ARUnit
 * Filename: ARUnit_SA1_SWC.h
 * Generated on: Wed May 1 6:2:58 EET
 ********************************************************************/

#include "Rte_SA1_SWC.h"	

#ifndef ARUNIT_SA1_SWC_H
#define ARUNIT_SA1_SWC_H

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef false
    #define false (0)
#endif
#ifndef true
    #define true  (!false)
#endif


void ARUnit_Initialize ();

/***************************************/
/******** Delegates API  ***************/
/***************************************/

/***************************************/
/******** Flags API  *******************/
/***************************************/

/***************************************/
/******** Implicit API  ****************/
/***************************************/
DECLSPEC_EXPORT void ARUnit_IWrite_SA1_SWC_GetDoorStatus_IO_SA1_PP_SA1_SWC_DoorStatus(uint8 DoorStatus);
DECLSPEC_EXPORT uint8 ARUnit_IRead_SA1_SWC_GetDoorStatus_IO_SA1_PP_SA1_SWC_DoorStatus(void);
DECLSPEC_EXPORT uint8* ARUnit_IWriteRef_SA1_SWC_GetDoorStatus_IO_SA1_PP_SA1_SWC_DoorStatus(void);
DECLSPEC_EXPORT void ARUnit_IWrite_SA1_SWC_GetDoorStatus_IO_SA1_RP_SA1_SWC_DoorStatus(uint8 DoorStatus);
DECLSPEC_EXPORT uint8 ARUnit_IRead_SA1_SWC_GetDoorStatus_IO_SA1_RP_SA1_SWC_DoorStatus(void);
DECLSPEC_EXPORT uint8* ARUnit_IWriteRef_SA1_SWC_GetDoorStatus_IO_SA1_RP_SA1_SWC_DoorStatus(void);
/***************************************/
/******** Explicit API  ****************/
/***************************************/
/***************************************/
/******** Runnable Calls****************/
/***************************************/

DECLSPEC_EXPORT void ARUnit_Trigger_SA1_SWC_GetDoorStatusFromIO(void);

#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* ARUNIT_SA1_SWC_H */
