/********************************************************************
 * Automatically generated by ARUnit
 * Filename: ARUnit_SA2_SWC_.c
 * Generated on: Wed May 1 6:2:58 EET
 ********************************************************************/

#include "string.h"
#include "ARUnit_SA2_SWC.h"


extern const Rte_CDS_SA2_SWC Rte_Instance_SA2_SWC;
extern const Rte_CDS_SA2_SWC * const Rte_Inst_SA2_SWC;


extern Std_ReturnType SA2_SWC_RP2_SA2_SWC_Led_Switch_Buffer_retcode;

extern FunctionPtr_SA2_SWC_RP2_SA2_SWC_Led_Switch Rte_Call_SA2_SWC_RP2_SA2_SWC_Led_Switch_Delegate;

DECLSPEC_EXPORT void ARUnit_IWrite_SA2_SWC_GetDoorStatus_RP1_SA2_SWC_LedStatus(uint8 LedStatus)
{
	(Rte_Inst_SA2_SWC)->GetDoorStatus_RP1_SA2_SWC_LedStatus->value = LedStatus;
}
DECLSPEC_EXPORT uint8* ARUnit_IWriteRef_SA2_SWC_GetDoorStatus_RP1_SA2_SWC_LedStatus(void)
{
	return &(Rte_Inst_SA2_SWC)->GetDoorStatus_RP1_SA2_SWC_LedStatus->value;
}
DECLSPEC_EXPORT uint8 ARUnit_IRead_SA2_SWC_GetDoorStatus_RP1_SA2_SWC_LedStatus(void)
{
	return (Rte_Inst_SA2_SWC)->GetDoorStatus_RP1_SA2_SWC_LedStatus->value;
}
DECLSPEC_EXPORT void ARUnit_Call_SA2_SWC_RP2_SA2_SWC_Led_Switch_ReturnCode(Std_ReturnType returnCode)
{
	SA2_SWC_RP2_SA2_SWC_Led_Switch_Buffer_retcode = returnCode;
}

DECLSPEC_EXPORT void ARUnit_Set_SA2_SWC_RP2_SA2_SWC_Led_Switch_Delegate(FunctionPtr_SA2_SWC_RP2_SA2_SWC_Led_Switch  delegate)
{
	Rte_Call_SA2_SWC_RP2_SA2_SWC_Led_Switch_Delegate = delegate;
}

DECLSPEC_EXPORT void ARUnit_Trigger_SA2_SWC_GetDoorStatusFromApp(void)
{
	GetDoorStatusFromApp();
}
