/********************************************************************
 * Automatically generated by ARUnit
 * Filename: ARUnit_Algo_App_SWC.h
 * Generated on: Wed May 1 6:2:58 EET
 ********************************************************************/

#include "Rte_Algo_App_SWC.h"	

#ifndef ARUNIT_ALGO_APP_SWC_H
#define ARUNIT_ALGO_APP_SWC_H

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef false
    #define false (0)
#endif
#ifndef true
    #define true  (!false)
#endif


void ARUnit_Initialize ();

/***************************************/
/******** Delegates API  ***************/
/***************************************/

/***************************************/
/******** Flags API  *******************/
/***************************************/

/***************************************/
/******** Implicit API  ****************/
/***************************************/
DECLSPEC_EXPORT void ARUnit_IWrite_Algo_App_SWC_GetDoorStatusRunnable_RP_APP_SWC_DoorStatus(uint8 DoorStatus);
DECLSPEC_EXPORT uint8 ARUnit_IRead_Algo_App_SWC_GetDoorStatusRunnable_RP_APP_SWC_DoorStatus(void);
DECLSPEC_EXPORT uint8* ARUnit_IWriteRef_Algo_App_SWC_GetDoorStatusRunnable_RP_APP_SWC_DoorStatus(void);
DECLSPEC_EXPORT void ARUnit_IWrite_Algo_App_SWC_GetDoorStatusRunnable_PP_APP_SWC_LedStatus(uint8 LedStatus);
DECLSPEC_EXPORT uint8 ARUnit_IRead_Algo_App_SWC_GetDoorStatusRunnable_PP_APP_SWC_LedStatus(void);
DECLSPEC_EXPORT uint8* ARUnit_IWriteRef_Algo_App_SWC_GetDoorStatusRunnable_PP_APP_SWC_LedStatus(void);
/***************************************/
/******** Explicit API  ****************/
/***************************************/
/***************************************/
/******** Runnable Calls****************/
/***************************************/

DECLSPEC_EXPORT void ARUnit_Trigger_Algo_App_SWC_GetDoorStatusFromSA1(void);

#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* ARUNIT_ALGO_APP_SWC_H */
