/********************************************************************
 * Automatically generated by ARUnit
 * Filename: ARUnit_IO_SWC.h
 * Generated on: Wed May 1 6:2:58 EET
 ********************************************************************/

#include "Rte_IO_SWC.h"	

#ifndef ARUNIT_IO_SWC_H
#define ARUNIT_IO_SWC_H

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef false
    #define false (0)
#endif
#ifndef true
    #define true  (!false)
#endif


void ARUnit_Initialize ();

/***************************************/
/******** Delegates API  ***************/
/***************************************/

/***************************************/
/******** Flags API  *******************/
/***************************************/

/***************************************/
/******** Implicit API  ****************/
/***************************************/
DECLSPEC_EXPORT void ARUnit_IWrite_IO_SWC_ReadDoorStatus_PP_IO_SWC_DoorStatus(uint8 DoorStatus);
DECLSPEC_EXPORT uint8 ARUnit_IRead_IO_SWC_ReadDoorStatus_PP_IO_SWC_DoorStatus(void);
DECLSPEC_EXPORT uint8* ARUnit_IWriteRef_IO_SWC_ReadDoorStatus_PP_IO_SWC_DoorStatus(void);
/***************************************/
/******** Explicit API  ****************/
/***************************************/
/***************************************/
/******** Runnable Calls****************/
/***************************************/
DECLSPEC_EXPORT Std_ReturnType ARUnit_Trigger_IO_SWC_LedSwitch(uint8 LedStatus);

DECLSPEC_EXPORT void ARUnit_Trigger_IO_SWC_SendDoorStatuToSA1(void);

#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* ARUNIT_IO_SWC_H */
